title:               Moroccan Olympiads in Informatics
url:                 https://portail.arena.moi

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

remote_theme: nicoelayda/celeste

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist